version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./monolith/postgres:/var/lib/postgresql/data

  monolith:
    image: node:latest
    container_name: monolith
    restart: always
    working_dir: /app
    volumes:
      - ./monolith:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - 3333:3333
  
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080